"""端口（抽象接口）：领域层只依赖这些 Protocol，infra/ 负责实现。

为什么放在 domain：这样 application/agents 层可以只对着接口写逻辑，
换存储/换模型/换检索都不影响业务代码，单元测试里也能塞假实现。
命名与前端 src/api/endpoints/*.ts 的资源划分一一对应，便于对照。
"""
from __future__ import annotations

from typing import Any, Protocol

from app.domain.entities import Claim, Finding, Report, ReviewAction, Task, TaskStage


class ReportRepository(Protocol):
    """研报与版本、原文块。对应 endpoints/reports.ts。"""

    async def ensure(self, project_id: str, report_path: str, **fields: Any) -> Report: ...
    async def get(self, report_id: str) -> Report | None: ...
    async def list(self, **filters: Any) -> tuple[list[Report], int]: ...
    async def create(self, **fields: Any) -> Report: ...
    async def list_blocks(self, report_id: str) -> list[Any]: ...
    async def list_claims(self, report_id: str) -> list[Claim]: ...


class ClaimRepository(Protocol):
    """主张、结论、证据。对应 endpoints/claims.ts。"""

    async def get_claim(self, claim_id: str) -> Claim | None: ...
    async def list_findings(self, claim_id: str) -> list[Finding]: ...
    async def get_finding(self, finding_id: str) -> Finding | None: ...
    async def append_review(self, claim_id: str, action: ReviewAction) -> ReviewAction: ...
    async def list_reviews(self, claim_id: str) -> list[ReviewAction]: ...


class TaskRepository(Protocol):
    """任务与阶段。对应 endpoints/tasks.ts。"""

    async def create(self, **fields: Any) -> Task: ...
    async def get(self, task_id: str) -> Task | None: ...
    async def list(self, **filters: Any) -> tuple[list[Task], int]: ...
    async def list_stages(self, task_id: str) -> list[TaskStage]: ...
    async def save_stage(self, stage: TaskStage) -> None: ...


class ProgressPublisher(Protocol):
    """任务进度发布（Redis pub/sub + 快照）。SSE 通道读它，前端进度条靠它。"""

    async def publish(self, task_id: str, event: str, data: dict[str, Any]) -> None: ...


class LlmGateway(Protocol):
    """LLM 网关：所有模型调用都从这里过（留痕、限流、schema 校验都在实现里做）。"""

    async def complete(self, prompt_key: str, variables: dict[str, Any], **opts: Any) -> str: ...


class Parser(Protocol):
    """文档解析：PDF/Word → 原文块列表（必须给出准确的字符区间）。"""

    async def parse(self, file_path: str) -> list[Any]: ...
